dist: trusty
language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  chrome: stable

install: yarn install --frozen-lockfile

script:
  - yarn ci:script
after_success:
  - yarn ci:after
