language: node_js
sudo: false
node_js:
  - '6.6.0'
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
  - master
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run coverage:check
  - npm run build
after_success:
  - npm run coverage:report
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
