language: node_js
node_js:
  - '6.6.0'
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - if [[ `node -v` == v4* ]]; then npm i -g npm@latest-3; fi
  - if [[ `node -v` == v6* ]]; then npm i -g npm@latest-4; fi
  - if [[ `node -v` == v8* ]]; then npm i -g npm@latest-5; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install: yarn --frozen-lockfile

script:
  - npm run ci:script
after_success:
  - npm run ci:after