dist: trusty
sudo: false
language: node_js
node_js:
  - '8.9.4'
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install: yarn install --frozen-lockfile

script:
  - yarn ci:script
after_success:
  - yarn ci:after
